name: Issue Reply
on:
  issues:
    types: [opened]
jobs:
  reply-helper:
    runs-on: ubuntu-latest
    steps:
      - name: help wanted
        uses: fentaniao/issues-action@v0.01
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: 'Fentaniao'
          body: |
            Hello, @${{ github.event.issue.user.login }}! Thank you very much for your issue, I will deal with these problems soon.