name: Issue Reply
on:
  issues:
    types: [opened]
jobs:
  reply-helper:
    runs-on: ubuntu-latest
    steps:
      - name: Comment to an open issue
        uses: Fentaniao/issues-action@0.01
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello, @${{ github.event.issue.user.login }}! Thank you very much for your issue, I will deal with these problems soon.
      - name: Add assigness
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: 'Fentaniao'